name: Say Hello World
on:
  issues:
    types:
      - opened

jobs:
  issuesOpened:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: yarn --frozen-lockfile
      - run: yarn build
      - uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
